language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html && pip install flake8 sphinx sphinx_rtd_theme tqdm matplotlib pillow tensorboardX sphinx-gallery ase codecov nose

jobs:
  include:
    - stage: flake8
      script: flake8 .
    - stage: unit test
      script: python setup.py nosetests
    - stage: tools
      script:
        - python tools/training-benchmark.py ./dataset/ani_gdb_s01.h5
        - python tools/neurochem-test.py ./dataset/ani_gdb_s01.h5
        - python tools/inference-benchmark.py --tqdm ./xyz_files/CH4-5.xyz
    - stage: runnable submodules
      script:
        - python -m torchani.neurochem.trainer --tqdm tests/test_data/inputtrain.ipt  dataset/ani_gdb_s01.h5 dataset/ani_gdb_s01.h5
        - python -m torchani.data.cache_aev tmp dataset/ani_gdb_s01.h5 256
    - stage: docs
      script: sphinx-build docs build