language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html && pip install flake8 sphinx sphinx_rtd_theme tqdm matplotlib pillow tensorboardX sphinx-gallery ase codecov nose pytorch-ignite

jobs:
  - script: flake8 .
  - script: python setup.py nosetests
  - script: python tools/training-benchmark.py ./dataset/ani_gdb_s01.h5
  - script: python tools/neurochem-test.py ./dataset/ani_gdb_s01.h5
  - script: python tools/inference-benchmark.py --tqdm ./xyz_files/CH4-5.xyz
  - script: python -m torchani.neurochem.trainer --tqdm tests/test_data/inputtrain.ipt  dataset/ani_gdb_s01.h5 dataset/ani_gdb_s01.h5
  - script: python -m torchani.data.cache_aev tmp dataset/ani_gdb_s01.h5 256
  - script: sphinx-build docs build